### ISSUE TITLE
Valve Index wakes up from standby while configuration tool is running

### ISSUE THREAD

**Issue by aurel42** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#19]
While the configuration tool is open and the headset not in use, the Valve Index headset is permanently going to stand-by and waking up again, the cycle repeats about every 10 seconds.

I'm unclear about actual usage. Does the configuration tool need to run permanently, or do I only use it to change the settings, or do I need to start it once per session?

**Comment by aurel42** [comment]
First reaction after starting MFS for the first time using the tool: *jaw drops on floor*
This is mindboggling.

**Comment by mbucchia** [comment]
> I'm unclear about actual usage. Does the configuration tool need to run permanently, or do I only use it to change the settings, or do I need to start it once per session?

Thanks for the report. Today the config tool is querying the OpenXR resolution every 10 seconds so it can display it. That's explains your wake up.

This functionality will be removed in the next version, because the resolution will be configurable from Inside the game.

You don't need to ever run the tool again once you've found your settings. So to avoid this issue, just close the tool once your done with the tweaking of the scaling/sharpness.

**Comment by aurel42** [comment]
Thank you <3

**Comment by mbucchia** [comment]
Closing as won't fix in this project. The OpenXR-Toolkit will not rely on the external config tool - hence not subject to the issue.
